version: 0.2

env:
  parameter-store:
    GoogleClientId: "google-client-id"
    AllowedEmails: "allowed-emails"
phases:
  install:
    commands:
      - echo AWS CLI v2 Install started on `date`
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ls -l /root/.pyenv/shims/aws
      - ./aws/install --bin-dir /root/.pyenv/shims --install-dir /usr/local/aws-cli --update
  pre_build:
    commands:
      - echo PreBuild started on `date`
      - npm install
      - sed -e s/{google-client-id}/${GoogleClientId}/ .env.replace > .env
      - sed -e s/{allowed-emails}/${AllowedEmails}/ .env.replace >> .env
      - cat .env
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - aws s3 sync build/ s3://s3-mtc-haba-link/
  post_build:
    commands:
      - echo Build completed on `date`
      - export DISTRIBUTION_ID=`aws cloudfront list-distributions | jq -r '.DistributionList.Items[0].Id'`
      - echo $DISTRIBUTION_ID
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
