version: 0.2

phases:
  pre_build:
    commands:
      - echo AWS CLI v2 Install started on `date`
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ls -l /root/.pyenv/shims/aws
      - ./aws/install --bin-dir /root/.pyenv/shims --install-dir /usr/local/aws-cli --update
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm run build
      - aws s3 sync build/ s3://s3-mtc-haba-link/
  post_build:
    commands:
      - echo Build completed on `date`
      - export DISTRIBUTION_ID=`aws cloudfront list-distributions | jq -r '.DistributionList.Items[0].Id'`
      - echo $DISTRIBUTION_ID
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
