AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # DNS Record Create
  CloudFrontDNSRecord:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !ImportValue MtcCfnRoute53ForSubDomain-HostedZoneId
      RecordSets:
        - Name: mtc.haba.link # SubDomain Name
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # CloudFront.netのホストゾーンIDを指定する必要あり
            DNSName: !ImportValue MtcCfnWeb-DomainName
